name: "Master"

on:
  workflow_dispatch:
  #push:
  #  branches: ["master"]
  #  paths:
  #    - ".github/workflows/test.yaml"
  #    - "dist/**"
  #    - "src/**"
  #    - "package*.json"
  #    - "requirements*.txt"
  #    - "action.yml"
  #    - "Dockerfile"

env:
  stack-name: "test_stack-context"

jobs:
  master:
    name: "Master"
    if: ${{ !contains(github.event.head_commit.message, '#notest') }}
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: "Checkout Pull"
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: "Debug CTX github"
        if: ${{ !github.event.act }}
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "Debug"
        continue-on-error: true
        run: |
          echo "pull_request.head.sha: ${{ github.event.pull_request.head.sha }}"

      - name: "1: Before Context"
        continue-on-error: true
        run: |
          docker context ls

      - name: "1: Docker Context"
        if: ${{ !cancelled() }}
        uses: cssnr/docker-context-action@master
        with:
          host: ${{ secrets.DOCKER_HOST }}
          #port: ${{ secrets.DOCKER_PORT }}
          user: ${{ secrets.DOCKER_USER }}
          pass: ${{ secrets.DOCKER_PASS }}
          #ssh_key: ${{ secrets.DOCKER_SSH_KEY }}

      - name: "1: After Context"
        run: |
          docker context ls
          #docker context inspect
          #docker info
          docker ps -f "name=${{ env.stack-name }}"

      - name: "2: Write YAML"
        if: ${{ !cancelled() }}
        uses: teunmooij/yaml@cffa9c57cc8d70f64b649ec07cab7e4c49d14ba1 # v1.0.1
        with:
          to-file: "docker-compose.yaml"
          data: |
            {"version":"3.8","services":{"alpine":{"image":"alpine:latest","command":"tail -f /dev/null"}}}

      - name: "2: Deploy Stack"
        run: |
          docker stack deploy -c docker-compose.yaml --detach=false "${{ env.stack-name }}"

      - name: "2: After Deploy"
        run: |
          docker ps -f "name=${{ env.stack-name }}"
          #docker stack rm "${{ env.stack-name }}"
